# Generated by Django 5.2.7 on 2026-08-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0020_achievement_portfolio_a_slug_e1985d_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="hero_badge",
            field=models.CharField(
                blank=True,
                default="Hello, I am",
                help_text="Hero top badge text",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="hero_description",
            field=models.TextField(
                blank=True, help_text="Hero section description pitch"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                help_text="Custom hero visual image",
                null=True,
                upload_to="hero/",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="hero_stat_1_icon",
            field=models.CharField(blank=True, default="fas fa-users", max_length=50),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="hero_stat_1_label",
            field=models.CharField(
                blank=True, default="Production Users", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="hero_stat_1_value",
            field=models.CharField(blank=True, default="1,000+", max_length=50),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="hero_stat_2_icon",
            field=models.CharField(blank=True, default="fas fa-id-card", max_length=50),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="hero_stat_2_label",
            field=models.CharField(
                blank=True, default="ID Cards Processed", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="hero_stat_2_value",
            field=models.CharField(blank=True, default="136K+", max_length=50),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="hero_stat_3_icon",
            field=models.CharField(
                blank=True, default="fas fa-cloud-download-alt", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="hero_stat_3_label",
            field=models.CharField(
                blank=True, default="Cards Downloaded", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="hero_stat_3_value",
            field=models.CharField(blank=True, default="86K+", max_length=50),
        ),
    ]
